UPDATE name_options
SET description = 
  CASE 
    WHEN name = 'Nova' THEN 'From Latin "novus" meaning "new". In astronomy, a nova is a star that suddenly bursts into brilliant luminescence after lying dormant. The name evokes transformation, radiance and new beginnings - perfect for a cat with a bright, energetic personality or one who lights up any room they enter. Pronounced NOH-vuh, with playful nicknames like Nov, Novi, or Va-Va. Especially fitting for cats with luminous eyes or coats, or those who grow more radiant as they gain confidence.'
    
    WHEN name = 'Umbra' THEN 'From Latin "umbra" meaning shadow or shade. In astronomy, the umbra appears in multiple celestial phenomena - it''s both the darkest part of a shadow during an eclipse and the central dark region of sunspots on our star''s surface. Pronounced UM-bruh, lending itself to nicknames like Uma, Bra, or Shadow. This elegant name suggests mystery and sophistication, ideal for a dark-coated or enigmatic cat who masters the art of stealth or finds peace in quiet corners. Especially meaningful for a cat from Helios, as the name connects to solar phenomena, bridging both shadow and light with scientific precision and gothic beauty.'
    
    WHEN name = 'Cosmo' THEN 'Derived from Greek "kosmos" meaning order or universe. Ancient philosophers like Pythagoras used this term to describe the harmonious nature of existence. Pronounced KAHZ-moh, with endearing nicknames like Cos, Cozzy, or Mo-Mo. Perfect for a wise, contemplative cat who seems to understand universal rhythms - especially fitting for cats with speckled coats like tiny galaxies or those with deep, knowing eyes who spend evenings stargazing from windowsills.'
    
    WHEN name = 'Ekko' THEN 'A modern twist on "echo", inspired by the Greek nymph Echo and popularized by the time-bending character from League of Legends. Pronounced EH-koh, with nicknames like Ek, Ko-Ko, or Ekks. Ideal for cats with impeccable timing who seem to anticipate needs before they arise, appear in multiple places almost simultaneously, or have distinctive vocal personalities. The name bridges mythological depth with contemporary cool.'
    
    WHEN name = 'Ozzy' THEN 'A name carrying both rock ''n'' roll spirit and ancient meaning, derived from Hebrew "Ozias" (God''s strength). Pronounced AH-zee, with variants like Oz, Ozz, or Ozman. Perfect for a cat with natural charisma and an independent streak - one who breaks conventional "cat rules" while maintaining an air of dignity. The name suggests both theatrical flair and quiet power, suited to cats who command attention without effort.'
    
    WHEN name = 'Syzygy' THEN 'From Greek "syzygos" meaning yoked together or union. In astronomy, describes the perfect alignment of celestial bodies - like when the Earth, Moon, and Sun align during eclipses, or when planets line up in rare configurations. Pronounced SIZ-ih-jee, with playful nicknames like Zy, Ziggy, or Sy. Ideal for cats who seem to understand invisible patterns or move with extraordinary grace. The name suggests cosmic harmony and perfect timing, especially fitting for cats with symmetrical markings or those who create their own sense of order in chaos.'
    
    WHEN name = 'Ifemi' THEN 'A beautiful Yoruba name meaning "love me" or "my love". Pronounced ee-FEH-mee, with sweet nicknames like Ife, Femi, or Mi-Mi. Perfect for an affectionate cat who forms deep emotional bonds - one who greets you at the door, sleeps curled against you, or purrs at the mere sight of their favorite human. The name carries generations of expressed affection, ideal for cats with gentle, nurturing personalities.'
    
    WHEN name = 'Orbit' THEN 'From Latin "orbita" meaning track or course. In celestial mechanics, describes the gravitational path one body follows around another. Pronounced OR-bit, with nicknames like Orby, Bit, or Obi. Perfect for energetic cats who create their own movement patterns - whether racing through the house in precise circuits or gracefully circling their favorite humans. The name suggests both playful motion and cosmic order.'
  END
WHERE name IN ('Nova', 'Umbra', 'Cosmo', 'Ekko', 'Ozzy', 'Syzygy', 'Ifemi', 'Orbit'); 